version: "3.7"

services:
  mysql:
    image: mysql:5.7
    tty: true
    stdin_open: true
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/conf:/etc/mysql/conf.d/
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=bobbob1234
      - TZ=Asia/Tokyo
      - MYSQL_DATABASE=offer_item
      - MYSQL_USER=root
      - MYSQL_PASSWORD=bobbob1234
volumes:
  mysql-data:
    name: offer-item-mysql-volume
