// Code generated by MockGen. DO NOT EDIT.
// Source: affiliate_item_adapter.go

// Package mock_adapter is a generated GoMock package.
package mock_adapter

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/terui-ryota/offer-item/internal/domain/model"
)

// MockAffiliateItemAdapter is a mock of AffiliateItemAdapter interface.
type MockAffiliateItemAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockAffiliateItemAdapterMockRecorder
}

// MockAffiliateItemAdapterMockRecorder is the mock recorder for MockAffiliateItemAdapter.
type MockAffiliateItemAdapterMockRecorder struct {
	mock *MockAffiliateItemAdapter
}

// NewMockAffiliateItemAdapter creates a new mock instance.
func NewMockAffiliateItemAdapter(ctrl *gomock.Controller) *MockAffiliateItemAdapter {
	mock := &MockAffiliateItemAdapter{ctrl: ctrl}
	mock.recorder = &MockAffiliateItemAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAffiliateItemAdapter) EXPECT() *MockAffiliateItemAdapterMockRecorder {
	return m.recorder
}

// BulkGetItems mocks base method.
func (m *MockAffiliateItemAdapter) BulkGetItems(ctx context.Context, itemIdentifiers model.ItemIdentifiers) (map[model.ItemIdentifier]model.Items, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkGetItems", ctx, itemIdentifiers)
	ret0, _ := ret[0].(map[model.ItemIdentifier]model.Items)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkGetItems indicates an expected call of BulkGetItems.
func (mr *MockAffiliateItemAdapterMockRecorder) BulkGetItems(ctx, itemIdentifiers interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkGetItems", reflect.TypeOf((*MockAffiliateItemAdapter)(nil).BulkGetItems), ctx, itemIdentifiers)
}

// GetItems mocks base method.
func (m *MockAffiliateItemAdapter) GetItems(ctx context.Context, itemIdentifier model.ItemIdentifier) (*model.Items, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItems", ctx, itemIdentifier)
	ret0, _ := ret[0].(*model.Items)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItems indicates an expected call of GetItems.
func (mr *MockAffiliateItemAdapterMockRecorder) GetItems(ctx, itemIdentifier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItems", reflect.TypeOf((*MockAffiliateItemAdapter)(nil).GetItems), ctx, itemIdentifier)
}
