// Code generated by gen-getter. DO NOT EDIT.
package model

func (a *AffiliatorProperty) AffiliatorID() AffiliatorID {
	return a.affiliatorID
}
func (a *AffiliatorProperty) MediaUserID() string {
	return a.mediaUserID
}
func (a *AffiliatorProperty) MediaURL() string {
	return a.mediaURL
}
func (a *AffiliatorProperty) Validity() AffiliatorValidity {
	return a.validity
}
