// Code generated by gen-getter. DO NOT EDIT.
package model

func (a *AffiliateItemCommission) Rate() *float32 {
	return a.rate
}
func (a *AffiliateItemCommission) Amount() *float32 {
	return a.amount
}
func (a *AffiliateItemCommission) RatePoint() *float32 {
	return a.ratePoint
}
func (a *AffiliateItemCommission) AmountPoint() *float32 {
	return a.amountPoint
}
func (a *AffiliateItemCommission) Price() *float32 {
	return a.price
}
func (a *AffiliateItemCommission) StaticRate() *float32 {
	return a.staticRate
}
func (a *AffiliateItemCommission) Description() string {
	return a.description
}
func (a *AffiliateItemCommission) CommissionType() CommissionType {
	return a.commissionType
}
