// Code generated by gen-getter. DO NOT EDIT.
package model

func (a *AffiliateItemItem) ItemId() ItemID {
	return a.itemId
}
func (a *AffiliateItemItem) ItemImage() string {
	return a.itemImage
}
func (a *AffiliateItemItem) ItemName() string {
	return a.itemName
}
func (a *AffiliateItemItem) ItemOwnerId() string {
	return a.itemOwnerId
}
func (a *AffiliateItemItem) LargeMaterialImage() string {
	return a.largeMaterialImage
}
func (a *AffiliateItemItem) MediumMaterialImage1() string {
	return a.mediumMaterialImage1
}
func (a *AffiliateItemItem) SmallMaterialImage1() string {
	return a.smallMaterialImage1
}
func (a *AffiliateItemItem) MediumMaterialImage2() string {
	return a.mediumMaterialImage2
}
func (a *AffiliateItemItem) MediumMaterialImage3() string {
	return a.mediumMaterialImage3
}
func (a *AffiliateItemItem) SmallMaterialImage2() string {
	return a.smallMaterialImage2
}
func (a *AffiliateItemItem) Price() []Price {
	return a.price
}
func (a *AffiliateItemItem) Commission() AffiliateItemCommission {
	return a.commission
}
func (a *AffiliateItemItem) RawItemUrl() string {
	return a.rawItemUrl
}
func (a *AffiliateItemItem) RawTrackingUrl() string {
	return a.rawTrackingUrl
}
func (a *AffiliateItemItem) ItemUrls() URLMap {
	return a.itemUrls
}
func (a *AffiliateItemItem) TrackingUrls() URLMap {
	return a.trackingUrls
}
func (a *AffiliateItemItem) ItemDescription() string {
	return a.itemDescription
}
func (a *AffiliateItemItem) DenialCondition() string {
	return a.denialCondition
}
func (a *AffiliateItemItem) ListingNgKeyWords() string {
	return a.listingNgKeyWords
}
func (a *AffiliateItemItem) ApproveWatiTime() string {
	return a.approveWatiTime
}
func (a *AffiliateItemItem) ContentName() string {
	return a.contentName
}
func (a *AffiliateItemItem) IsDF() bool {
	return a.isDF
}
