// Code generated by gen-getter. DO NOT EDIT.
package model

import "time"

func (a *AffiliateItemDFItem) DfItemId() AffiliateItemDFItemID {
	return a.dfItemId
}
func (a *AffiliateItemDFItem) DfItemCode() string {
	return a.dfItemCode
}
func (a *AffiliateItemDFItem) DfItemName() string {
	return a.dfItemName
}
func (a *AffiliateItemDFItem) RawDFItemUrl() string {
	return a.rawDFItemUrl
}
func (a *AffiliateItemDFItem) RawTrackingUrl() string {
	return a.rawTrackingUrl
}
func (a *AffiliateItemDFItem) DfItemUrls() URLMap {
	return a.dfItemUrls
}
func (a *AffiliateItemDFItem) TrackingUrls() URLMap {
	return a.trackingUrls
}
func (a *AffiliateItemDFItem) Material() MaterialList {
	return a.material
}
func (a *AffiliateItemDFItem) Brand() string {
	return a.brand
}
func (a *AffiliateItemDFItem) ShopName() string {
	return a.shopName
}
func (a *AffiliateItemDFItem) ShopCode() string {
	return a.shopCode
}
func (a *AffiliateItemDFItem) ItemId() ItemID {
	return a.itemId
}
func (a *AffiliateItemDFItem) DfItemPriceList() AffiliateItemDFItemPriceList {
	return a.dfItemPriceList
}
func (a *AffiliateItemDFItem) Commission() AffiliateItemCommissionList {
	return a.commission
}
func (a *AffiliateItemDFItem) EndDate() time.Time {
	return a.endDate
}
func (a *AffiliateItemDFItem) Active() bool {
	return a.active
}
func (a *AffiliateItemDFItem) UpdatedDate() time.Time {
	return a.updatedDate
}
func (a *AffiliateItemDFItem) Hash() string {
	return a.hash
}
func (a *AffiliateItemDFItem) ModifiedDate() *time.Time {
	return a.modifiedDate
}
func (a *AffiliateItemDFItem) Review() *Review {
	return a.review
}
func (a *AffiliateItemDFItem) IsFavorited() bool {
	return a.isFavorited
}
func (a *AffiliateItemDFItem) GeneralRateInfo() *GeneralRateInfo {
	return a.generalRateInfo
}
func (a *AffiliateItemDFItem) SalePriceLabel() string {
	return a.salePriceLabel
}
