// Code generated by gen-getter. DO NOT EDIT.
package model

import "time"

func (a *Assignee) ID() AssigneeID {
	return a.id
}
func (a *Assignee) OfferItemID() OfferItemID {
	return a.offerItemID
}
func (a *Assignee) AmebaID() AmebaID {
	return a.amebaID
}
func (a *Assignee) WritingFee() int {
	return a.writingFee
}
func (a *Assignee) Stage() Stage {
	return a.stage
}
func (a *Assignee) DeclineReason() *string {
	return a.declineReason
}
func (a *Assignee) CreatedAt() time.Time {
	return a.createdAt
}
