// Code generated by gen-getter. DO NOT EDIT.
package model

func (a *AssigneeOfferItemPair) Assignee() *Assignee {
	return a.assignee
}
func (a *AssigneeOfferItemPair) OfferItem() *OfferItem {
	return a.offerItem
}
