// Code generated by gen-getter. DO NOT EDIT.
package model

func (c *Commission) CommissionType() CommissionType {
	return c.commissionType
}
func (c *Commission) CalculatedRate() float32 {
	return c.calculatedRate
}
