// Code generated by gen-getter. DO NOT EDIT.
package model

func (d *DFItem) ID() DFItemID {
	return d.id
}
func (d *DFItem) Img() string {
	return d.img
}
func (d *DFItem) Name() string {
	return d.name
}
func (d *DFItem) MinCommissionRate() *Commission {
	return d.minCommissionRate
}
func (d *DFItem) MaxCommissionRate() *Commission {
	return d.maxCommissionRate
}
func (d *DFItem) Urls() []*PlatformURL {
	return d.urls
}
