// Code generated by gen-getter. DO NOT EDIT.
package model

func (i *Item) ID() ItemID {
	return i.id
}
func (i *Item) Img() string {
	return i.img
}
func (i *Item) Name() string {
	return i.name
}
func (i *Item) MinCommissionRate() *Commission {
	return i.minCommissionRate
}
func (i *Item) MaxCommissionRate() *Commission {
	return i.maxCommissionRate
}
func (i *Item) Urls() []*PlatformURL {
	return i.urls
}
func (i *Item) HasTieup() bool {
	return i.hasTieup
}
func (i *Item) ContentName() string {
	return i.contentName
}
func (i *Item) EnabledSelfBack() bool {
	return i.enabledSelfBack
}
func (i *Item) IsDF() bool {
	return i.isDF
}
