// Code generated by gen-getter. DO NOT EDIT.
package model

func (m *MailParams) OfferItem() *OfferItem {
	return m.offerItem
}
func (m *MailParams) Assignee() *Assignee {
	return m.assignee
}
func (m *MailParams) Examination() *Examination {
	return m.examination
}
