// Code generated by gen-getter. DO NOT EDIT.
package model

import "time"

func (o *OfferItem) Name() string {
	return o.name
}
func (o *OfferItem) ID() OfferItemID {
	return o.id
}
func (o *OfferItem) Item() *Item {
	return o.item
}
func (o *OfferItem) DfItem() *DFItem {
	return o.dfItem
}
func (o *OfferItem) CouponBannerID() *BannerID {
	return o.couponBannerID
}
func (o *OfferItem) SpecialRate() float64 {
	return o.specialRate
}
func (o *OfferItem) SpecialAmount() int {
	return o.specialAmount
}
func (o *OfferItem) HasSample() bool {
	return o.hasSample
}
func (o *OfferItem) NeedsPreliminaryReview() bool {
	return o.needsPreliminaryReview
}
func (o *OfferItem) NeedsAfterReview() bool {
	return o.needsAfterReview
}
func (o *OfferItem) NeedsPRMark() bool {
	return o.needsPRMark
}
func (o *OfferItem) PostRequired() bool {
	return o.postRequired
}
func (o *OfferItem) HasLottery() bool {
	return o.hasLottery
}
func (o *OfferItem) PostTarget() PostTarget {
	return o.postTarget
}
func (o *OfferItem) HasCoupon() bool {
	return o.hasCoupon
}
func (o *OfferItem) HasSpecialCommission() bool {
	return o.hasSpecialCommission
}
func (o *OfferItem) ProductFeatures() string {
	return o.productFeatures
}
func (o *OfferItem) CautionaryPoints() string {
	return o.cautionaryPoints
}
func (o *OfferItem) ReferenceInfo() string {
	return o.referenceInfo
}
func (o *OfferItem) OtherInfo() string {
	return o.otherInfo
}
func (o *OfferItem) IsInvitationMailSent() bool {
	return o.isInvitationMailSent
}
func (o *OfferItem) IsOfferDetailMailSent() bool {
	return o.isOfferDetailMailSent
}
func (o *OfferItem) IsPassedPreliminaryReviewMailSent() bool {
	return o.isPassedPreliminaryReviewMailSent
}
func (o *OfferItem) IsFailedPreliminaryReviewMailSent() bool {
	return o.isFailedPreliminaryReviewMailSent
}
func (o *OfferItem) IsArticlePostMailSent() bool {
	return o.isArticlePostMailSent
}
func (o *OfferItem) IsPassedAfterReviewMailSent() bool {
	return o.isPassedAfterReviewMailSent
}
func (o *OfferItem) IsFailedAfterReviewMailSent() bool {
	return o.isFailedAfterReviewMailSent
}
func (o *OfferItem) IsClosed() bool {
	return o.isClosed
}
func (o *OfferItem) CreatedAt() time.Time {
	return o.createdAt
}
func (o *OfferItem) Schedules() ScheduleList {
	return o.schedules
}
func (o *OfferItem) DraftedItemInfo() *ItemInfo {
	return o.draftedItemInfo
}
func (o *OfferItem) PickInfo() *PickInfo {
	return o.pickInfo
}
