// Code generated by gen-getter. DO NOT EDIT.
package model

func (p *PickInfo) ItemID() ItemID {
	return p.itemID
}
func (p *PickInfo) DfItemID() *DFItemID {
	return p.dfItemID
}
func (p *PickInfo) BannerIDs() []BannerID {
	return p.bannerIDs
}
