// Code generated by gen-getter. DO NOT EDIT.
package model

func (q *QuestionAnswer) AssigneeID() AssigneeID {
	return q.assigneeID
}
func (q *QuestionAnswer) QuestionID() QuestionID {
	return q.questionID
}
func (q *QuestionAnswer) OfferItemID() OfferItemID {
	return q.offerItemID
}
func (q *QuestionAnswer) Content() string {
	return q.content
}
