// Code generated by gen-getter. DO NOT EDIT.
package model

func (q *Questionnaire) OfferItemID() OfferItemID {
	return q.offerItemID
}
func (q *Questionnaire) Description() string {
	return q.description
}
func (q *Questionnaire) Questions() []Question {
	return q.questions
}
