// Code generated by gen-getter. DO NOT EDIT.
package model

func (q *Question) ID() QuestionID {
	return q.id
}
func (q *Question) OfferItemID() OfferItemID {
	return q.offerItemID
}
func (q *Question) QuestionType() QuestionType {
	return q.questionType
}
func (q *Question) Title() string {
	return q.title
}
func (q *Question) ImageURL() string {
	return q.imageURL
}
func (q *Question) Options() []string {
	return q.options
}
