// Code generated by gen-getter. DO NOT EDIT.
package model

import "time"

func (s *Schedule) ID() ScheduleID {
	return s.id
}
func (s *Schedule) OfferItemID() OfferItemID {
	return s.offerItemID
}
func (s *Schedule) ScheduleType() ScheduleType {
	return s.scheduleType
}
func (s *Schedule) StartDate() *time.Time {
	return s.startDate
}
func (s *Schedule) EndDate() *time.Time {
	return s.endDate
}
