// Code generated by gen-getter. DO NOT EDIT.
package model

func (s *SendQueueParam) OfferItemID() string {
	return s.offerItemID
}
func (s *SendQueueParam) AssigneeID() string {
	return s.assigneeID
}
func (s *SendQueueParam) AdsTemplateCode() string {
	return s.adsTemplateCode
}
