// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

var TableNames = struct {
	Assignee                    string
	AssigneeLog                 string
	DraftedItemInfo             string
	Examination                 string
	OfferItem                   string
	Questionnaire               string
	QuestionnaireQuestion       string
	QuestionnaireQuestionAnswer string
	Schedule                    string
}{
	Assignee:                    "assignee",
	AssigneeLog:                 "assignee_log",
	DraftedItemInfo:             "drafted_item_info",
	Examination:                 "examination",
	OfferItem:                   "offer_item",
	Questionnaire:               "questionnaire",
	QuestionnaireQuestion:       "questionnaire_question",
	QuestionnaireQuestionAnswer: "questionnaire_question_answer",
	Schedule:                    "schedule",
}
