// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Questionnaire is an object representing the database table.
type Questionnaire struct {
	OfferItemID string `boil:"offer_item_id" json:"offer_item_id" toml:"offer_item_id" yaml:"offer_item_id"`
	Description string `boil:"description" json:"description" toml:"description" yaml:"description"`

	R *questionnaireR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L questionnaireL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var QuestionnaireColumns = struct {
	OfferItemID string
	Description string
}{
	OfferItemID: "offer_item_id",
	Description: "description",
}

var QuestionnaireTableColumns = struct {
	OfferItemID string
	Description string
}{
	OfferItemID: "questionnaire.offer_item_id",
	Description: "questionnaire.description",
}

// Generated where

var QuestionnaireWhere = struct {
	OfferItemID whereHelperstring
	Description whereHelperstring
}{
	OfferItemID: whereHelperstring{field: "`questionnaire`.`offer_item_id`"},
	Description: whereHelperstring{field: "`questionnaire`.`description`"},
}

// QuestionnaireRels is where relationship names are stored.
var QuestionnaireRels = struct {
	OfferItem string
}{
	OfferItem: "OfferItem",
}

// questionnaireR is where relationships are stored.
type questionnaireR struct {
	OfferItem *OfferItem `boil:"OfferItem" json:"OfferItem" toml:"OfferItem" yaml:"OfferItem"`
}

// NewStruct creates a new relationship struct
func (*questionnaireR) NewStruct() *questionnaireR {
	return &questionnaireR{}
}

func (r *questionnaireR) GetOfferItem() *OfferItem {
	if r == nil {
		return nil
	}
	return r.OfferItem
}

// questionnaireL is where Load methods for each relationship are stored.
type questionnaireL struct{}

var (
	questionnaireAllColumns            = []string{"offer_item_id", "description"}
	questionnaireColumnsWithoutDefault = []string{"offer_item_id", "description"}
	questionnaireColumnsWithDefault    = []string{}
	questionnairePrimaryKeyColumns     = []string{"offer_item_id"}
	questionnaireGeneratedColumns      = []string{}
)

type (
	// QuestionnaireSlice is an alias for a slice of pointers to Questionnaire.
	// This should almost always be used instead of []Questionnaire.
	QuestionnaireSlice []*Questionnaire
	// QuestionnaireHook is the signature for custom Questionnaire hook methods
	QuestionnaireHook func(context.Context, boil.ContextExecutor, *Questionnaire) error

	questionnaireQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	questionnaireType                 = reflect.TypeOf(&Questionnaire{})
	questionnaireMapping              = queries.MakeStructMapping(questionnaireType)
	questionnairePrimaryKeyMapping, _ = queries.BindMapping(questionnaireType, questionnaireMapping, questionnairePrimaryKeyColumns)
	questionnaireInsertCacheMut       sync.RWMutex
	questionnaireInsertCache          = make(map[string]insertCache)
	questionnaireUpdateCacheMut       sync.RWMutex
	questionnaireUpdateCache          = make(map[string]updateCache)
	questionnaireUpsertCacheMut       sync.RWMutex
	questionnaireUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var questionnaireAfterSelectMu sync.Mutex
var questionnaireAfterSelectHooks []QuestionnaireHook

var questionnaireBeforeInsertMu sync.Mutex
var questionnaireBeforeInsertHooks []QuestionnaireHook
var questionnaireAfterInsertMu sync.Mutex
var questionnaireAfterInsertHooks []QuestionnaireHook

var questionnaireBeforeUpdateMu sync.Mutex
var questionnaireBeforeUpdateHooks []QuestionnaireHook
var questionnaireAfterUpdateMu sync.Mutex
var questionnaireAfterUpdateHooks []QuestionnaireHook

var questionnaireBeforeDeleteMu sync.Mutex
var questionnaireBeforeDeleteHooks []QuestionnaireHook
var questionnaireAfterDeleteMu sync.Mutex
var questionnaireAfterDeleteHooks []QuestionnaireHook

var questionnaireBeforeUpsertMu sync.Mutex
var questionnaireBeforeUpsertHooks []QuestionnaireHook
var questionnaireAfterUpsertMu sync.Mutex
var questionnaireAfterUpsertHooks []QuestionnaireHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Questionnaire) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range questionnaireAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Questionnaire) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range questionnaireBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Questionnaire) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range questionnaireAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Questionnaire) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range questionnaireBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Questionnaire) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range questionnaireAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Questionnaire) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range questionnaireBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Questionnaire) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range questionnaireAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Questionnaire) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range questionnaireBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Questionnaire) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range questionnaireAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddQuestionnaireHook registers your hook function for all future operations.
func AddQuestionnaireHook(hookPoint boil.HookPoint, questionnaireHook QuestionnaireHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		questionnaireAfterSelectMu.Lock()
		questionnaireAfterSelectHooks = append(questionnaireAfterSelectHooks, questionnaireHook)
		questionnaireAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		questionnaireBeforeInsertMu.Lock()
		questionnaireBeforeInsertHooks = append(questionnaireBeforeInsertHooks, questionnaireHook)
		questionnaireBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		questionnaireAfterInsertMu.Lock()
		questionnaireAfterInsertHooks = append(questionnaireAfterInsertHooks, questionnaireHook)
		questionnaireAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		questionnaireBeforeUpdateMu.Lock()
		questionnaireBeforeUpdateHooks = append(questionnaireBeforeUpdateHooks, questionnaireHook)
		questionnaireBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		questionnaireAfterUpdateMu.Lock()
		questionnaireAfterUpdateHooks = append(questionnaireAfterUpdateHooks, questionnaireHook)
		questionnaireAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		questionnaireBeforeDeleteMu.Lock()
		questionnaireBeforeDeleteHooks = append(questionnaireBeforeDeleteHooks, questionnaireHook)
		questionnaireBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		questionnaireAfterDeleteMu.Lock()
		questionnaireAfterDeleteHooks = append(questionnaireAfterDeleteHooks, questionnaireHook)
		questionnaireAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		questionnaireBeforeUpsertMu.Lock()
		questionnaireBeforeUpsertHooks = append(questionnaireBeforeUpsertHooks, questionnaireHook)
		questionnaireBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		questionnaireAfterUpsertMu.Lock()
		questionnaireAfterUpsertHooks = append(questionnaireAfterUpsertHooks, questionnaireHook)
		questionnaireAfterUpsertMu.Unlock()
	}
}

// One returns a single questionnaire record from the query.
func (q questionnaireQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Questionnaire, error) {
	o := &Questionnaire{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "entity: failed to execute a one query for questionnaire")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Questionnaire records from the query.
func (q questionnaireQuery) All(ctx context.Context, exec boil.ContextExecutor) (QuestionnaireSlice, error) {
	var o []*Questionnaire

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "entity: failed to assign all query results to Questionnaire slice")
	}

	if len(questionnaireAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Questionnaire records in the query.
func (q questionnaireQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to count questionnaire rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q questionnaireQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "entity: failed to check if questionnaire exists")
	}

	return count > 0, nil
}

// OfferItem pointed to by the foreign key.
func (o *Questionnaire) OfferItem(mods ...qm.QueryMod) offerItemQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.OfferItemID),
	}

	queryMods = append(queryMods, mods...)

	return OfferItems(queryMods...)
}

// LoadOfferItem allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (questionnaireL) LoadOfferItem(ctx context.Context, e boil.ContextExecutor, singular bool, maybeQuestionnaire interface{}, mods queries.Applicator) error {
	var slice []*Questionnaire
	var object *Questionnaire

	if singular {
		var ok bool
		object, ok = maybeQuestionnaire.(*Questionnaire)
		if !ok {
			object = new(Questionnaire)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeQuestionnaire)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeQuestionnaire))
			}
		}
	} else {
		s, ok := maybeQuestionnaire.(*[]*Questionnaire)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeQuestionnaire)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeQuestionnaire))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &questionnaireR{}
		}
		args[object.OfferItemID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &questionnaireR{}
			}

			args[obj.OfferItemID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`offer_item`),
		qm.WhereIn(`offer_item.id in ?`, argsSlice...),
		qmhelper.WhereIsNull(`offer_item.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load OfferItem")
	}

	var resultSlice []*OfferItem
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice OfferItem")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for offer_item")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for offer_item")
	}

	if len(offerItemAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.OfferItem = foreign
		if foreign.R == nil {
			foreign.R = &offerItemR{}
		}
		foreign.R.Questionnaire = object
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.OfferItemID == foreign.ID {
				local.R.OfferItem = foreign
				if foreign.R == nil {
					foreign.R = &offerItemR{}
				}
				foreign.R.Questionnaire = local
				break
			}
		}
	}

	return nil
}

// SetOfferItem of the questionnaire to the related item.
// Sets o.R.OfferItem to related.
// Adds o to related.R.Questionnaire.
func (o *Questionnaire) SetOfferItem(ctx context.Context, exec boil.ContextExecutor, insert bool, related *OfferItem) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `questionnaire` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"offer_item_id"}),
		strmangle.WhereClause("`", "`", 0, questionnairePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.OfferItemID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.OfferItemID = related.ID
	if o.R == nil {
		o.R = &questionnaireR{
			OfferItem: related,
		}
	} else {
		o.R.OfferItem = related
	}

	if related.R == nil {
		related.R = &offerItemR{
			Questionnaire: o,
		}
	} else {
		related.R.Questionnaire = o
	}

	return nil
}

// Questionnaires retrieves all the records using an executor.
func Questionnaires(mods ...qm.QueryMod) questionnaireQuery {
	mods = append(mods, qm.From("`questionnaire`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`questionnaire`.*"})
	}

	return questionnaireQuery{q}
}

// FindQuestionnaire retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindQuestionnaire(ctx context.Context, exec boil.ContextExecutor, offerItemID string, selectCols ...string) (*Questionnaire, error) {
	questionnaireObj := &Questionnaire{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `questionnaire` where `offer_item_id`=?", sel,
	)

	q := queries.Raw(query, offerItemID)

	err := q.Bind(ctx, exec, questionnaireObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "entity: unable to select from questionnaire")
	}

	if err = questionnaireObj.doAfterSelectHooks(ctx, exec); err != nil {
		return questionnaireObj, err
	}

	return questionnaireObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Questionnaire) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("entity: no questionnaire provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(questionnaireColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	questionnaireInsertCacheMut.RLock()
	cache, cached := questionnaireInsertCache[key]
	questionnaireInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			questionnaireAllColumns,
			questionnaireColumnsWithDefault,
			questionnaireColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(questionnaireType, questionnaireMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(questionnaireType, questionnaireMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `questionnaire` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `questionnaire` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `questionnaire` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, questionnairePrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "entity: unable to insert into questionnaire")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.OfferItemID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "entity: unable to populate default values for questionnaire")
	}

CacheNoHooks:
	if !cached {
		questionnaireInsertCacheMut.Lock()
		questionnaireInsertCache[key] = cache
		questionnaireInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Questionnaire.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Questionnaire) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	questionnaireUpdateCacheMut.RLock()
	cache, cached := questionnaireUpdateCache[key]
	questionnaireUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			questionnaireAllColumns,
			questionnairePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("entity: unable to update questionnaire, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `questionnaire` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, questionnairePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(questionnaireType, questionnaireMapping, append(wl, questionnairePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update questionnaire row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by update for questionnaire")
	}

	if !cached {
		questionnaireUpdateCacheMut.Lock()
		questionnaireUpdateCache[key] = cache
		questionnaireUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q questionnaireQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update all for questionnaire")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to retrieve rows affected for questionnaire")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o QuestionnaireSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("entity: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), questionnairePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `questionnaire` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, questionnairePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update all in questionnaire slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to retrieve rows affected all in update all questionnaire")
	}
	return rowsAff, nil
}

var mySQLQuestionnaireUniqueColumns = []string{
	"offer_item_id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Questionnaire) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("entity: no questionnaire provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(questionnaireColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLQuestionnaireUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	questionnaireUpsertCacheMut.RLock()
	cache, cached := questionnaireUpsertCache[key]
	questionnaireUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			questionnaireAllColumns,
			questionnaireColumnsWithDefault,
			questionnaireColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			questionnaireAllColumns,
			questionnairePrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("entity: unable to upsert questionnaire, could not build update column list")
		}

		ret := strmangle.SetComplement(questionnaireAllColumns, strmangle.SetIntersect(insert, update))

		cache.query = buildUpsertQueryMySQL(dialect, "`questionnaire`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `questionnaire` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(questionnaireType, questionnaireMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(questionnaireType, questionnaireMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "entity: unable to upsert for questionnaire")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(questionnaireType, questionnaireMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "entity: unable to retrieve unique values for questionnaire")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "entity: unable to populate default values for questionnaire")
	}

CacheNoHooks:
	if !cached {
		questionnaireUpsertCacheMut.Lock()
		questionnaireUpsertCache[key] = cache
		questionnaireUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Questionnaire record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Questionnaire) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("entity: no Questionnaire provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), questionnairePrimaryKeyMapping)
	sql := "DELETE FROM `questionnaire` WHERE `offer_item_id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete from questionnaire")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by delete for questionnaire")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q questionnaireQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("entity: no questionnaireQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete all from questionnaire")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by deleteall for questionnaire")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o QuestionnaireSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(questionnaireBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), questionnairePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `questionnaire` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, questionnairePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete all from questionnaire slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by deleteall for questionnaire")
	}

	if len(questionnaireAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Questionnaire) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindQuestionnaire(ctx, exec, o.OfferItemID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *QuestionnaireSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := QuestionnaireSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), questionnairePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `questionnaire`.* FROM `questionnaire` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, questionnairePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "entity: unable to reload all in QuestionnaireSlice")
	}

	*o = slice

	return nil
}

// QuestionnaireExists checks if the Questionnaire row exists.
func QuestionnaireExists(ctx context.Context, exec boil.ContextExecutor, offerItemID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `questionnaire` where `offer_item_id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, offerItemID)
	}
	row := exec.QueryRowContext(ctx, sql, offerItemID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "entity: unable to check if questionnaire exists")
	}

	return exists, nil
}

// Exists checks if the Questionnaire row exists.
func (o *Questionnaire) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return QuestionnaireExists(ctx, exec, o.OfferItemID)
}
